### ISSUE TITLE
Output sections not appearing in outcome class synopsis

### ISSUE THREAD

**Issue by ned14** [standardese/standardese#104]
If you look at https://ned14.github.io/outcome/reference/outcome/#standardese-outcome_v2_xxx__outcome-R-S-P-NoValuePolicy-, only the very first output section appears. The rest do not.

**Comment by foonathan** [comment]
Are those standalone output sections? I.e. are they not part of a comment that is part of an entity?

**Comment by ned14** [comment]
The outcome source code has broken up all the member functions into output sections, same as for result. But they do not appear in outcome, unlike result.

**Comment by foonathan** [comment]
What I meant is:

```
 /// \output_section Converting constructors ---- This is a standalone comment!
  /*! Converting constructor to a successful outcome.
  \tparam 1
  \exclude
  \param 1
  \exclude
  \param t The value from which to initialise the `value_type`.
  \effects Initialises the outcome with a `value_type`.
  \requires Type T is implicitly constructible to `value_type`, is not implicitly constructible to `error_type`, is not implicitly constructible to `exception_type` and is not `outcome<R, S, P>` and not `in_place_type<>`.
  \throws Any exception the construction of `value_type(T)` might throw.
  */
  OUTCOME_TEMPLATE(class T)
  OUTCOME_TREQUIRES(OUTCOME_TPRED(predicate::template enable_value_converting_constructor<T>))
  constexpr outcome(T &&t, value_converting_constructor_tag /*unused*/ = value_converting_constructor_tag()) noexcept(std::is_nothrow_constructible<value_type, T>::value)  // NOLINT
  : base{in_place_type<typename base::_value_type>, std::forward<T>(t)},
    _ptr()
  {
    using namespace hooks;
    hook_outcome_construction(this, std::forward<T>(t));
}
```

Comments are now handled by cppast, so standardese either gets the comment of an entity or a container containing all unmatched comments, like the output section. It then tries to match them to an entity using the `\entity`, `\file` commands etc. But it can't do that here, so it will issue a warning an ignore the comment.

I'll see whether I can support your style of output sections.

**Comment by saraedum** [comment]
I don't understand what this issue was about really and the original link is gone. Feel free to open a new issue if you don't want this to disappear.
