### ISSUE TITLE
entities list shows items defined out of line from class and without documentation

### ISSUE THREAD

**Issue by ned14** [standardese/standardese#109]
You can see it at https://ned14.github.io/status-code/, scroll to the bottom. As you'll see in https://github.com/ned14/status-code/blob/master/include/status_code.hpp, this is happening for member functions defined out of line only. I am on latest develop branch.

**Comment by saraedum** [comment]
I am not entirely sure what this issue is about. If someone can create a short reproducer, I might be able to look into it. But for the moment, I'll just close this very old issue.
