### ISSUE TITLE
LLVM binary directory defaults to "C:\Program Files\LLVM\bin\" on windows

### ISSUE THREAD

**Issue by nicobako** [standardese/standardese#111]
I keep getting this error :
```
Command 'C:/Program Files/LLVM/bin/clang++.exe -E -CC -Wno-pragma-once-outside-header "-x" "c++" "-I" "C:\Program Files\LLVM\lib\clang\3.9.0\include" "-std=c++14" "-fms-extensions" "-fms-compatibility" "-fms-compatibility-version=19" nbt/ascii/Conversions.hpp' failed with exit code '-1'
```
I don't have administrative privileges on my work computer, so I can't *install* clang. As a result, LLVM is not in the location that standardese.exe expects.

It would be very helpful to be able to change the LLVM directories via the command line or config file.

Thanks

**Comment by foonathan** [comment]
Are you using the prebuilt binary? Try compiling it from source (develop branch is nicer anyway)

**Comment by nicobako** [comment]
Yes i am. I will try that tomorrow and tell you if it works.

**Comment by foonathan** [comment]
On Windows you don't have it anyway. You can set other variables instead, look at the readme for cppast or the appveyor.yml.

**Comment by foonathan** [comment]
(I will also continue working on it now and provide more pre built binaries)
