### ISSUE TITLE
Docker distribution suggestion

### ISSUE THREAD

**Issue by alexpana** [standardese/standardese#124]
Just a suggestion: I think a better docker use case would be to bundle the standardese binary inside the image, and then mount the source code and the documentation directory when running the container. The container would parse the sources mounted and write the documentation in the mounted output directory. 

This is better aligned with the usage of docker as just an isolated process, keeps the system cleaner by not requiring you to install the output binary, and it also avoids problems where the container environment differs from the host, making the compiled binary incompatible with the host (like missing dependency libraries, or incompatible library versions, etc.)

**Comment by saraedum** [comment]
I agree. I am trying to make this happen for the 0.4.0 release.

**Comment by saraedum** [comment]
@alexpana: It would be great if you could have a look at https://github.com/standardese/standardese/pull/150. Is that what you had in mind?

**Comment by alexpana** [comment]
Yes, that's what I had in mind. Would be great if it didn't require 350Mb for a 2Mb binary, but from what I see that won't be trivial since all of the fat comes directly from the clang dependency.
