### ISSUE TITLE
standardese does not compile thanks to -Werror

### ISSUE THREAD

**Issue by jansende** [standardese/standardese#133]
The development branch of standardese does not compile thanks to the `-Werror` option in line 115 of `external/cppast/src/CMakeLists.txt`.

The actual warning emitted is:
```bash
/home/user/standardese/external/cppast/src/libclang/type_parser.cpp:524:13: warning: 15 enumeration values not handled in switch: 'CXType_ObjCObject', 'CXType_ObjCTypeParam', 'CXType_Attributed'...
      [-Wswitch]
    switch (type.kind)
            ^
1 warning generated.
```

This probably can be fixed by patching the cppast library. The better approach however, would be to remove `-Werror` entirely.

**Comment by saraedum** [comment]
@jansende I believe that this an issue with cppast. If it's still an issue, you should probably file an issue there.

**Comment by jansende** [comment]
I think so. I originally posted it here because the developer was the same. If the error doesn't occur anymore, feel free to close it.
