### ISSUE TITLE
Remove patreon link from README

### ISSUE THREAD

**Issue by saraedum** [standardese/standardese#134]
and maybe update a few other things that need to change now that standardese has been moved to a new namespace (i.e., github organization.)

**Comment by cata0309** [comment]
Why removing the patreon link ?!? There must be a way to give back to him for creating this tool. I don't support your idea. What namespace has Standardese moved to ?

**Comment by saraedum** [comment]
Thanks for your feedback @cata0309. It's good we clarify these things.

> Why removing the patreon link ?!? There must be a way to give back to him for creating this tool.

The patreon link is meant as a support per productive week. Since @foonathan stated that he probably won't work on standardese in the future, it does not work in its current setup at least.

>  I don't support your idea.

Not sure what "your" refers to. It's not my idea. @foonathan suggested it https://github.com/standardese/standardese/issues/125#issuecomment-537608900

> What namespace has Standardese moved to ?

I don't understand what you mean, could you clarify?

**Comment by cata0309** [comment]
I understand now ! You should clarify the 'new namespace' as you used it when you opened the issue. That's why I asked!
