### ISSUE TITLE
Static Documentation/Website

### ISSUE THREAD

**Issue by saraedum** [standardese/standardese#135]
It would be nice if standardese had a static standardese.github.io webpage with documentation. Probably parts of it should be generated with standardese.

**Comment by saraedum** [comment]
@bresilla documentation can live in a separate repo sure. During a CI run we should probably inject standardese's own reference (created by standardese) and upload everything to github pages.

**Comment by bresilla** [comment]
@saraedum Perfect!
Well, i assume in the very beginning we should have a simple site that people can see how to use and what we're doing, then we'll definitely integrate Standardese own's documentation output and a CI run checker for it (or something between those lines).

So I'll jump into it right away and then see where we go :)

**Comment by saraedum** [comment]
I'll close this since we now have a dedicated repo for that. Let's discuss further ideas there.
