### ISSUE TITLE
A couple of bugs. Willing to help

### ISSUE THREAD

**Issue by tobiashienzsch** [standardese/standardese#194]
Hi Everyone,

first of all I would like to thank you all for the work you have put into this project. I am currently trying to replace doxygen with standardese in my project: [github.com/tobanteEmbedded/tetl](https://github.com/tobanteEmbedded/tetl). The first impression is definitely great. Unfortunately there are still some error messages and warnings when I generate my documentation. Probably it makes sense to split each problem into separate issues later. I wanted to collect all my problems in this issue first, so you can get an overview. 

I am definitely willing to do some work myself. But since I don't have any experience with the inner workings of standardese, I need your help to find the right places. 

1. [My Pipeline](#my-pipeline)
2. [Missing Files](#missing-files)
3. [Macro Expansion](#macro-expansion)
4. [Duplicate Parameter Registration](#duplicate-parameter-registration)
5. [Parsing Problems](#parsing-problems)

Greetings,

Toby

## My Pipeline

- Create markdown files using `standardese v0.5`
- Run post-processing python script
- Add markdown files to hugo project
- Build static files using hugo
- Demo: [tobanteembedded.github.io/tetl-docs](https://tobanteembedded.github.io/tetl-docs)

```sh
cd tetl/
mkdir cmake-build-docs
cd cmake-build-docs
standardese --config $(shell realpath ./standardese.ini) -I $(shell realpath .) -DTETL_RTOS_USE_STUBS=1 $(shell realpath ./etl)
./scripts/standardese-md.py
```

## Missing Files

**Problem:** For some files from my library no documentation is generated. An examples is [etl/string.hpp](https://tobanteembedded.github.io/tetl-docs/docs/doc_string), which only generates markdown for the `#include` statements. Even tough there are a lot of entities inside the file. Source: [etl/string.hpp](https://github.com/tobanteEmbedded/tetl/blob/main/etl/string.hpp). If I run `standardese` only on the problematic file I get no warnings or errors. Even in verbose mode.

## Macro Expansion

**Problem:** If I set `show_macro_replacement=false` `standardese` still shows the replacements in the generated markdown files. 
**Example:**

```cpp
// In source code
TETL_REQUIRES(is_copy_constructible_v<T> || is_move_constructible_v<T>)
constexpr static_vector(etl::static_vector::size_type n) 

// In generated markdown
template <int _concept_requires_656 = 42, ::etl::enable_if_t<(_concept_requires_656 == 43) || (is_copy_constructible_v<T> || is_move_constructible_v<T>), int> = 0>
constexpr static_vector(etl::static_vector::size_type n) 
```

## Duplicate Parameter Registration

**Generated Docs:** [tobanteembedded.github.io/tetl-docs/docs/doc_cstdarg/](https://tobanteembedded.github.io/tetl-docs/docs/doc_cstdarg/)
**Source File:** [etl/cstdarg.hpp](https://github.com/tobanteEmbedded/tetl/blob/main/etl/cstdarg.hpp)
**Problem:** When using the same argument name in multiple macro definitions, I get the following error message:

```sh
[standardese linker] [warning] va_end: duplicate registration of link name 'ap'
```

## Parsing Problems

**Problem:** The following entities result in warnings. As far as I can tell, that is a limitation of `libclang` and there is nothing that `cppast` & `standardese` can do about it.

```sh
# Dduction Guide
[libclang parser] [error] /home/tobante/Developer/tobanteEmbedded/tetl/etl/array.hpp:290: unexpected template cursor kind

# Inline variable template
/home/tobante/Developer/tobanteEmbedded/tetl/etl/memory.hpp:190: unhandled cursor of kind 'UnexposedDecl'
```

**Comment by saraedum** [comment]
@tobiashienzsch thanks for this detailed description and for offering your help :)

I try to be on gitter https://gitter.im/foonathan/standardese frequently. If that works for you, maybe we can discuss what could be done about these issue there?

**Comment by saraedum** [comment]
This is now #198, #197, #196, #195.
