### ISSUE TITLE
Support for LaTeX in Documentation Comments

### ISSUE THREAD

**Issue by nilsdeppe** [standardese/standardese#53]
Support for LaTeX in documentation comments would be extremely useful for scientific or math-heavy code bases. It doesn't look like CommonMark supports this yet. Doxygen supports [LaTeX formulas](http://www.stack.nl/~dimitri/doxygen/manual/formulas.html) using the following syntax:

```
\f$\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}\f$
```

Supporting this syntax would be quite useful.

**Comment by foonathan** [comment]
There are two issues that needs to be solved (+ an implementation change):

1) I need some LaTeX parser library, not going to roll my own.

2) I need some way to render LaTeX inside HTML or Markdown output.

**Comment by nilsdeppe** [comment]
Yes, definitely agree with not rolling your own parser. LaTeX seems pretty horrible. It looks like [pandoc](http://pandoc.org/) would possibly offer something. Another option may be to treat the LaTeX as text, so a regex for say `\f$` and then defer the rendering of it to something like MathJax. That is probably the easiest solution.

From what I was able to find looking into this earlier today MathJax is easiest for HTML. CommonMark doesn't appear to have any LaTeX support, but [kramdown](https://kramdown.gettalong.org/syntax.html#math-blocks) does. I believe [Jekyll](https://jekyllrb.com/docs/extras/) takes this approach and I've had it worked extremely well, even with very complicated physics equations.

**Comment by nilsdeppe** [comment]
I just looked at MathJax a bit more and what works is adding

```html
<style TYPE="text/css">
code.has-jax {font: inherit; font-size: 100%; background: inherit; border: inherit;}
</style>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'] // removed 'code' entry
    }
});
MathJax.Hub.Queue(function() {
    var all = MathJax.Hub.getAllJax(), i;
    for(i = 0; i < all.length; i += 1) {
        all[i].SourceElement().parentNode.className += ' has-jax';
    }
});
</script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
```

to the top of one of the generated html files and then writing equations as `$x^2$` for inline and `$$x^2$$` for multiline equations. To be Doxygen compliant it would be good to use the `\f$` syntax for inline and then change it to `$` during processing so MathJax handles it correctly. Similarly, replacing `\f[` and `\f]` with `$$` during processing should enable support for multiline equations in the same way it is supported in Doxygen. Alternatively, MathJax can be configured to directly accept the `\f$` token by changing the `inlineMath` config above. This would be really excellent initial support that could later be extended to be compatible with more Doxygen code.

I can look into further configuring MathJax to provide better support for what is commonly used in physics and mathematics if MathJax seems a promising avenue of approach. Thoughts on this idea?

**Comment by acgetchell** [comment]
+1 for MathJax. +1 for Doxygen compliance so I don't have to rewrite all my comments. +\$infty$ for LaTeX comments in code.

**Comment by foonathan** [comment]
I'm currently working on something else, so this might take a while though.

**Comment by nilsdeppe** [comment]
@foonathan would you be opposed to having a header.html hold the MathJax JS and have that be linked into the other HTML files? I have yet to find a good way to support this in MarkDown, unfortunately.

**Comment by foonathan** [comment]
I'd prefer a solution that seems less hacky.

**Comment by nilsdeppe** [comment]
Sounds good. I'll try to dig into what Doxygen is doing next week.

**Comment by nilsdeppe** [comment]
I just looked into what Doxygen does for LaTeX. It first replaces the `\f$` comments with `\(` so MathJax recognizes it, i.e. `\f$x^i\f$` to `\(x^i\)`. For separate line comments denoted by `\f[` in Doxygen documentation it uses

```html
<p class="formulaDsp">
\[ J^I{}_i = \frac{\partial \xi^I}{\partial x^i} \]
</p>
```

In the CSS file it adds:

```css
p.formulaDsp {
	text-align: center;
}

img.formulaDsp {
	
}
```

to handle these. This approach would mean extending the parser to handle the Doxygen LaTeX syntax and output the correct HTML + MathJax, but that should be manageable. The required JS for MathJax then is quite minimal:
```html
<script type="text/x-mathjax-config">
  MathJax.Hub.Config({
    extensions: ["tex2jax.js"],
    jax: ["input/TeX","output/HTML-CSS"],
});
</script><script src="http://cdn.mathjax.org/mathjax/latest/MathJax.js"></script>
```
would be added to the header of every HTML file.

@foonathan what do you think about this approach? Markdown is still a concern, but it seems that CommonMark doesn't (yet) have support for LaTeX and I'm not sure how well loading JS in MD works.

**Comment by gmgunter** [comment]
Hi there, has there been any progress on this? I'd love to give standardese a try but lack of support for math expressions is a big blocker for my project.

**Comment by saraedum** [comment]
@gmgunter It depends on what you are trying to achieve exactly. If you can use standard MathJax syntax, then you only need to include the correct script tags somehow. I don't think any specific standardese support is needed for that use case. (But it would be great to document this approach properly.)

So, for example, I am usually creating Markdown files with standardese and then render these out with jekyll. I have jekyll include these lines somewhere in the output to make `$$ math $$` render with MathJax:

```
  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3.0.1/es5/tex-mml-chtml.js"></script>
```

If that would work for you, I could set up a sample repository where this is done.

**Comment by gmgunter** [comment]
Thanks for the tip, @saraedum. MathJax support is all I need so this sounds like a great solution for me. An example repository would be much appreciated.

**Comment by saraedum** [comment]
@gmgunter please have a look at https://github.com/standardese/standardese/pull/176 for a demo repository.
