### ISSUE TITLE
Prebuilt binaries should use 100% static libraries

### ISSUE THREAD

**Issue by ned14** [standardese/standardese#61]
Right now there is at least a dependency on libclang.dll. That sucks. I'd like the prebuilt binaries to be 100% free of all shared library dependencies. 100% statically linked.

And ideally auto regenerated per commit by CI so my other CI jobs can go fetch "latest standardese executable" and rebuild my docs.

**Comment by foonathan** [comment]
libclang.dll should be the only dependency, don't know how to get rid of it.

Where would I put the per-commit binary? I currently attach them to the release.

**Comment by ned14** [comment]
> libclang.dll should be the only dependency, don't know how to get rid of it.

Just build it into a static library instead of a shared library.

> Where would I put the per-commit binary? I currently attach them to the release.

There are lots of options :). I personally dump them onto one of my servers at https://dedi4.nedprod.com/static/files/ but many people fire them onto a sub-$15/year (yes, per year) VPS https://lowendbox.com/. You can also push them onto CDash, or one of the many other free binary distro websites.

**Comment by foonathan** [comment]
> Just build it into a static library instead of a shared library.

I don't built it, I download the precompiiled binaries.

>  I personally dump them onto one of my server

That could work, I'll do it after all my offline changes are integrated into standardese.

**Comment by vinniefalco** [comment]
I would like this as well

**Comment by vinniefalco** [comment]
>Where would I put the per-commit binary?

What is a per-commit binary?

**Comment by njlr** [comment]
Yes! I had to patch the binary to find `libclang.dylib` correctly.

**Comment by saraedum** [comment]
Since we are not shipping pre-built binaries anymore, I'll close this issue.
