### ISSUE TITLE
Variable templates are not parsed correctly

### ISSUE THREAD

**Issue by ned14** [standardese/standardese#76]
I know this is a limitation of libclang, but it's annoying.

**Comment by Arthapz** [comment]
Hi, i obtain

> [libclang parser] [warning] /home/arthapz/Dev/repos/stormkit/core/include/storm/core/TypeTraits.hpp:47: unhandled cursor of kind 'UnexposedDecl'

on variable templates

**Comment by saraedum** [comment]
I am not entirely sure what this issue is about. If someone can create a short reproducer, I might be able to look into it. But for the moment, I'll just close this very old issue.
